export interface Room {
  id?: number; // Optional, since the ID is generated by the backend
  numeroChambre: number; // Room number
  type: string; // Type of the room (you might want to use an enum or string literals)
  prix: number; // Price of the room
  etat: string; // Status of the room (e.g., available, booked, etc.)
  description: string; // Description of the room
  photos: string[]; // Photos (optional, depending on how the backend returns the photos)
}
