[build]
builder = "NIXPACKS"
buildCommand = "cd BackPFE && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd BackPFE && java -Dserver.port=$PORT -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10